### ISSUE TITLE
Netdata Agent installation fails to compile libwebsockets and produce a Netdata.cloud capable agent

### ISSUE THREAD

**Issue by krital** [netdata/netdata#10297]
##### OS / Environment

```
Darwin alexs-mac-pro.lan 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

##### Steps To Reproduce

1. sudo ./netdata-installer.sh --install /usr/local
2. While building libwebsockets we get:

[  1%] Building C object CMakeFiles/websockets.dir/lib/core/alloc.c.o
In file included from /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-libwebsockets-XXXXXX.pH7jClqv/libwebsockets-3.2.2/lib/core/alloc.c:1:
In file included from /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-libwebsockets-XXXXXX.pH7jClqv/libwebsockets-3.2.2/lib/core/private.h:119:
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-libwebsockets-XXXXXX.pH7jClqv/libwebsockets-3.2.2/lib/plat/unix/private.h:164:9: error:
      'MSG_NOSIGNAL' macro redefined [-Werror,-Wmacro-redefined]
#define MSG_NOSIGNAL SO_NOSIGPIPE
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/sys/socket.h:584:9: note:
      previous definition is here
#define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */
        ^
1 error generated.
make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2

-----
Note: This seems to be caused by libwebsockets 3.2.2 which the installer uses with a hard dependency. If cloned the specific branch and I got a similar error which has not been fixed in that version but does not exist in latest version of libwebsockets which is 4.1. Not sure if there is a reason for sticking to the old version but in this case we need to patch it because MSG_NOSIGNAL does not exist on OSX OR the include header order needs to be adjusted to prevent the redefinition.

##### Expected behavior

Expected behaviour was to result in an agent that works with Netdata.cloud out of the box.

**Comment by underhood** [comment]
@kaskavel During your tests after recent Mac fixes what was Mac OS version you used? (I try to find what is the difference here) Did you use system libwebsockets or the one build by installer?

**Comment by kaskavel** [comment]
@underhood the MacOS version was identical (10.15.7) also I see that I use libwebsockets-3.2.2 in building. The only difference I can recall is that I had to install cmake for the installation to be successful. 

@krital may I propose to run a 'brew install cmake' and try again?

**Comment by krital** [comment]
I already have the latest version of cmake. As i mentioned above libwebsockets 3.2.2 fails to compile on its own with the same error message:

/Users/krital/dev/libwebsockets/lib/plat/unix/private.h:167:9: error: 'MSG_NOSIGNAL' macro redefined
      [-Werror,-Wmacro-redefined]
#define MSG_NOSIGNAL SO_NOSIGPIPE
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/sys/socket.h:584:9: note:
      previous definition is here
#define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */
        ^
In file included from /Users/krital/dev/libwebsockets/lib/core/alloc.c:1:
In file included from /Users/krital/dev/libwebsockets/lib/core/private.h:130:
In file included from /Users/krital/dev/libwebsockets/include/libwebsockets.h:576:

**Comment by kaskavel** [comment]
I have tried the installation after updating to latest version of xcode and indeed I verify the same behavior on my machine as well. 

Two things to note here: 

a) A fix should be planned for the libwebsockets build failure in this particular case 
b) A future CI for iOS platforms should take into account the xcode version of the system

**Comment by krital** [comment]
With regards to libwebsockets fix does this mean we will open a new issue or handle here?

With regards to CI I suggest we aim to support latest version of Xcode plus 2 previous releases. We would need a separate OSX VM for each versions as we can have more than one installed AFAIK.

**Comment by Ferroin** [comment]
@krital Can you check if LWS 3.2.3 has the same build issue as 3.2.2? Long term we need to be on LWS 4.x, but short term if 3.2.3 works we can upgrade that without having to worry about rigorous testing to the same degree as switching to using 4.x would warrant.

**Comment by kaskavel** [comment]
@Ferroin I did try LWS 3.2.3 and I get the same error:

/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/sys/socket.h:584:9: note: previous definition is here
#define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */

I am however in position to build successfully the latest LWS (4.1.6).

**Comment by Ferroin** [comment]
OK, the issue is I’m not entirely sure if we actually work correctly with LWS 4.1. @underhood do you know for certain if 4.1 works correctly for us?

**Comment by underhood** [comment]
should after my fixes. Let me find that PR with list of tested versions

**Comment by underhood** [comment]
https://github.com/netdata/netdata/pull/9984
latest tested is `4.1.4` but I remember going version by version and testing. Tested build && node connects to cloud and works. Didn't test long term stability.... so there might be some issues that show up.

**Comment by underhood** [comment]
oh yes it's there in the comment. Tested:
`3.2.2`, `4.1.0`, `4.1.1`, `4.1.2`, `4.1.3`, `4.1.4`
But again testing here means builds and connects to cloud (maybe 5 minutes scrolling cloud dashboard)

**Comment by krital** [comment]
This fixes the compilation problem for me:

diff --git a/lib/plat/unix/private.h b/lib/plat/unix/private.h
index 5b3281d6..43e69544 100644
--- a/lib/plat/unix/private.h
+++ b/lib/plat/unix/private.h
@@ -164,6 +164,8 @@ delete_from_fd(const struct lws_context *context, int fd);
  * but happily have something equivalent in the SO_NOSIGPIPE flag.
  */
 #ifdef __APPLE__
+/* iOS SDK 12+ seems to define it, undef it for compatibility both ways */
+#undef MSG_NOSIGNAL
 #define MSG_NOSIGNAL SO_NOSIGPIPE
 #endif

(Got it from the 4.x branch)

**Comment by underhood** [comment]
@krital if that is also fix from upstream we should go ahead and put it in our fork and create new release... I can do that after meeting today

**Comment by krital** [comment]
well they seem to have simply added an undef because on IOS12+ it is already defined so i did the same on my local header of 3.2.2 and it compiled. So if we could patch that header before we build we might be done

**Comment by underhood** [comment]
@Ferroin what you think?
1. fork websockets and patch
2. update websockets to 4.1 and test properly to ensure no regressions
3. patch by installer? (seems bit hacky to me, but let's consider)

**Comment by Ferroin** [comment]
2 is the best log-term option, we need to be on 4.x anyway to get bug fixes.

3 is actually not all that difficult for our usage, we don’t even need a custom patch file (we can embed it as a heredoc in the installer script itself).

**Comment by krital** [comment]
For a tactical solution I prefer solution 3 especially if its so easy

**Comment by underhood** [comment]
what i do not like about 3 is added level of obscurity... in few months everybody will forget there is patch added in installer...
@Ferroin can we prepare PR with some version of LWS 4.1 and test it? In case we find any nontrivial to fix trouble we revert to patching.

**Comment by krital** [comment]
Indeed but the aim here is to fix the agent working for OSX as fast as possible and with the least amount of risk. We won't leave it like that because we have your work on ACLK-NG / Paho client spike etc. If you think though that this an equally fast and safer approach lets do it.

**Comment by underhood** [comment]
@krital @Ferroin ok, lets go with patch then

**Comment by Ferroin** [comment]
I still think we should verify support for 4.1 and start using that if it works, but I agree that patching at build time is a beter option as a quick fix.

**Comment by underhood** [comment]
@Ferroin lets go ahead with #10333 as quick fix for this release. After this release is done we can make PR to use new LWS 4.1 and let us test it for few weeks (until next release). Should give us enough time to test and release with next agent version.

**Comment by krital** [comment]
I think that keeping our old patched libMosquitto but upgrading to latest libWebsockets is going to unchartered waters for no reason. I would rather move our patch to the latest versions instead.

**Comment by underhood** [comment]
Well updating libMosquitto is much higher risk than updating libWebsockets but certainly thing to consider.
But also thinking of ACLK-NG and maybe in future paho-c not sure how high prio to put on this. We will see as the situation evolves
