### ISSUE TITLE
Undefined reference after running make check in 1.19.0

### ISSUE THREAD

**Issue by Ikke** [netdata/netdata#7607]
Hello,

I'm maintaining netdata for Alpine Linux. After upgrading from 1.18.1 to 1.19.0, `make check` fails with some undefined references:

```
  CCLD     web/api/tests/valid_urls_testdriver
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/web_api_testdriver.fhjKCn.ltrans0.ltrans.o: in function `web_client_process_url':                                                               
<artificial>:(.text+0x1e58): undefined reference to `__wrap_web_client_api_request_v1'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: <artificial>:(.text+0x1f9e): undefined reference to `__wrap_rrdhost_find_by_hostname'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: <artificial>:(.text+0x1fb1): undefined reference to `__wrap_rrdhost_find_by_guid'                                                                    
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/web_api_testdriver.fhjKCn.ltrans0.ltrans.o: in function `api_info':
<artificial>:(.text+0x40fa): undefined reference to `__wrap_rrdpush_receiver_thread_spawn'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:3327: web/api/tests/web_api_testdriver] Error 1
make[3]: *** Waiting for unfinished jobs....                                                                           
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/valid_urls_testdriver.pGGAgH.ltrans0.ltrans.o: in function `web_client_process_url':
<artificial>:(.text+0x27bc): undefined reference to `__wrap_web_client_api_request_v1'                                 
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: <artificial>:(.text+0x2902): undefined reference to `__wrap_rrdhost_find_by_hostname'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: <artificial>:(.text+0x2915): undefined reference to `__wrap_rrdhost_find_by_guid'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/valid_urls_testdriver.pGGAgH.ltrans0.ltrans.o: in function `web_client_process_request':                                                         
<artificial>:(.text+0x3d41): undefined reference to `__wrap_rrdpush_receiver_thread_spawn'
collect2: error: ld returned 1 exit status 
```
Any idea what might be causing this?

The [APKBUILD](https://git.alpinelinux.org/aports/tree/testing/netdata/APKBUILD)

**Comment by Ikke** [comment]
This appears to only happen on x86_64. Other arches don't have any issue.

See: https://gitlab.alpinelinux.org/kdaudt/aports/pipelines/3863

**Comment by Ikke** [comment]
It only failed in my test environment. The official build completed just fine. Closing this issue.
