### ISSUE TITLE
netdata does not compile on FreeBSD 11.2-RELEASE-p4

### ISSUE THREAD

**Issue by rsyncOSX** [netdata/netdata#4393]
--- plugins/freebsd.plugin/freebsd_sysctl.o ---
  CC       plugins/freebsd.plugin/freebsd_sysctl.o
In file included from plugins/freebsd.plugin/../../common.h:14:0,
                 from plugins/freebsd.plugin/plugin_freebsd.h:6,
                 from plugins/freebsd.plugin/freebsd_sysctl.c:3:
plugins/freebsd.plugin/freebsd_sysctl.c: In function 'do_net_inet_icmp_stats':
plugins/freebsd.plugin/../../database/rrd.h:702:85: error: expected expression before ',' token
     rrdset_create_custom(host, type, id, name, family, context, title, units, plugin, module, priority, update_every, chart_type, (host)->rrd_memory_mode, (host)->rrd_history_entries)

**Comment by ktsaou** [comment]
fixed it with PR #4398 
Will be merged in a while.
Sorry for that!

**Comment by ktsaou** [comment]
Merged it.
Just update and it should compile.
