### ISSUE TITLE
[Bug]: error on '/usr/libexec/netdata/plugins.d/ndsudo ssacli-controllers-info': exit status 4

### ISSUE THREAD

**Issue by shalak** [netdata/netdata#18188]
### Bug description

After updating netdata to v1.46.2, I noticed that the old hpssa python plugin no longer works. I noticed that it has been [recently removed](https://github.com/netdata/netdata/pull/17638).

I disabled the `hpssa: yes` in `/etc/netdata/python.d.conf`, and went for [the new one in go](https://learn.netdata.cloud/docs/collecting-metrics/storage,-mount-points-and-filesystems/hpe-smart-arrays). Since it no longer needs sudo, I deleted the `netdata ALL=(root) NOPASSWD: /usr/sbin/ssacli` sudoers drop-in file.

Unfortunately, the HP widget does not appear, I followed the troubleshooting and I see the following errors in `./go.d.plugin -d -m hpssa`:

```
DBG jobmgr/manager.go:122 received configs: 1/+1/-0 ('/usr/lib/netdata/conf.d/go.d/hpssa.conf') component="job manager"
CONFIG go.d:collector:hpssa:hpssa create accepted job /collectors/jobs stock 'discoverer=file_reader,file=/usr/lib/netdata/conf.d/go.d/hpssa.conf' 'schema get enable disable update restart test userconfig' 0x0000 0x0000

DBG jobmgr/manager.go:293 creating hpssa[hpssa] job, config: map[__provider__:file reader __source__:discoverer=file_reader,file=/usr/lib/netdata/conf.d/go.d/hpssa.conf __source_type__:stock autodetection_retry:0 module:hpssa name:hpssa priority:70000 update_every:10] component="job manager"
DBG hpssa/exec.go:38 executing '/usr/libexec/netdata/plugins.d/ndsudo ssacli-controllers-info' collector=hpssa job=hpssa
ERR hpssa/hpssa.go:83 error on '/usr/libexec/netdata/plugins.d/ndsudo ssacli-controllers-info': exit status 4 collector=hpssa job=hpssa
ERR module/job.go:238 check failed collector=hpssa job=hpssa
CONFIG go.d:collector:hpssa:hpssa delete
```

### Expected behavior

HP SSA works correctly

### Steps to reproduce

1. Enable go `hpssa` plugin

### Installation method

kickstart.sh

### System info

```shell
Linux <myhostname> 6.8.8-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.8-2 (2024-06-24T09:00Z) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="12"
/etc/os-release:VERSION="12 (bookworm)"
/etc/os-release:VERSION_CODENAME=bookworm
/etc/os-release:ID=debian
```
```


### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.46.2
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : debian 12
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.8.8-2-pve
    Operating System ___________________________________________ : Debian GNU/Linux
    Operating System ID ________________________________________ : debian
    Operating System ID Like ___________________________________ : unknown
    Operating System Version ___________________________________ : 12 (bookworm)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 32
    CPU Frequency ______________________________________________ : 2300000000
    RAM Bytes __________________________________________________ : 75928190976
    Disk Capacity ______________________________________________ : 17243206467584
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine (compression) _____________________________________ : YES (zstd lz4)
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : YES
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

I noticed this only after upgrading my OS from bullseye to bookworm, don't know if this dist-upgrade was related.

**Comment by ilyam8** [comment]
I think that means that the “ssacli” binary is not in PATH. Can you execute that ndsudo command from the terminal and share the output?

**Comment by shalak** [comment]
It is in PATH, however only root can execute it:

```
[23:24:59][root@mymachine]:/usr/libexec/netdata/plugins.d# sudo -u netdata -s
netdata@mymachine:/usr/libexec/netdata/plugins.d$ /usr/libexec/netdata/plugins.d/ndsudo ssacli-controllers-info
ssacli : not available in PATH.
netdata@mymachine:/usr/libexec/netdata/plugins.d$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
netdata@mymachine:/usr/libexec/netdata/plugins.d$ /usr/sbin/ssacli
bash: /usr/sbin/ssacli: Permission denied
netdata@mymachine:/usr/libexec/netdata/plugins.d$ ls -al /usr/sbin/ssacli
-r-x------ 1 root root 174 kwi 14  2022 /usr/sbin/ssacli
netdata@mymachine:/usr/libexec/netdata/plugins.d$
```

Shouldn't `ndsudo` elevate the privileges to root and be able to run this binary anyway?

**Comment by ilyam8** [comment]
Thanks for reporting the issue, @shalak. Fixed in #18189.

**Comment by shalak** [comment]
Thanks for the quick fix! How can I find out when the change will be available in stable netdata build?

**Comment by ilyam8** [comment]
Fixed in v1.46.3.
