### ISSUE TITLE
Check about how to handle systems with libwebsockets version <3.X.X

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#8018]
##### Feature idea summary

* Define the oldest version we need to support.
* Find out which changes occurred in which version.
* Some functions have changed names.
* Ring-buffer support was added, how to support in previous versions?
* How to handle missing functions?

As @stelfrag pointed out on Ubuntu (in his case Ubuntu 19.10) there is no libwebsockets 3 currently present. Current ACLK MQTT/LWS code can work only with libwebsockets 3. Check how to best handle this.

**Comment by stelfrag** [comment]
The way mosquitto handles it (the support of lws in the broker with older version) is in  `mosquitto_broker_internal.h`. There it remaps the available functions from a previous version to the new one 

Of course not all of them will be available (like the ring buffer functions)

sample below

```
if defined(LWS_LIBRARY_VERSION_NUMBER)

define libwebsocket_callback_on_writable(A, B) lws_callback_on_writable
define libwebsocket_service(A, B) lws_service((A), (B))
define libwebsocket_create_context(A) lws_create_context((A))
define libwebsocket_context_destroy(A) lws_context_destroy((A))
define libwebsocket_write(A, B, C, D) lws_write((A), (B), (C), (D))
define libwebsocket_get_socket_fd(A) lws_get_socket_fd((A))
define libwebsockets_return_http_status(A, B, C, D) lws_return_http_sta
define libwebsockets_get_protocol(A) lws_get_protocol((A))
define libwebsocket_context lws_context
define libwebsocket_protocols lws_protocols
define libwebsocket_callback_reasons lws_callback_reasons
define libwebsocket lws
```

**Comment by underhood** [comment]
I just 5 minutes ago get my VM ready with `Ubuntu 18.04 LTS` and luckily it is not all `lws_*` functions. There seems to be mainly the ringbuffer missing (which I can pull into the code base and compile if older version is detected).

Then some defines are missing etc. but good news is it is not all/everything (so we no need to rewrite or keep separate version for older websockets). I will have to anyway within this issue investigate more in detail and fix it and also do full test with ubuntu version.

Full output of compile on Ubuntu 18.04 LTS.
```text
aclk/aclk_lws_wss_client.c: In function '_aclk_lws_wss_read_buffer_clear':
aclk/aclk_lws_wss_client.c:63:17: warning: implicit declaration of function 'lws_ring_get_count_waiting_elements' [-Wimplicit-function-declaration]
  size_t elems = lws_ring_get_count_waiting_elements(ringbuffer, NULL);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aclk/aclk_lws_wss_client.c:64:2: warning: implicit declaration of function 'lws_ring_consume'; did you mean 'lws_get_context'? [-Wimplicit-function-declaration]
  lws_ring_consume(ringbuffer, NULL, NULL, elems);
  ^~~~~~~~~~~~~~~~
  lws_get_context
aclk/aclk_lws_wss_client.c: At top level:
aclk/aclk_lws_wss_client.c:91:12: warning: excess elements in struct initializer
   0, 0, 0, 0
            ^
aclk/aclk_lws_wss_client.c:91:12: note: (near initialization for 'protocols[0]')
aclk/aclk_lws_wss_client.c:93:28: warning: excess elements in struct initializer
  { NULL, NULL, 0, 0, 0, 0, 0 }
                            ^
aclk/aclk_lws_wss_client.c:93:28: note: (near initialization for 'protocols[1]')
aclk/aclk_lws_wss_client.c: In function 'aclk_lws_wss_client_init':
aclk/aclk_lws_wss_client.c:120:26: warning: implicit declaration of function 'lws_ring_create'; did you mean 'arl_create'? [-Wimplicit-function-declaration]
  inst->read_ringbuffer = lws_ring_create(1, ACLK_LWS_WSS_RECV_BUFF_SIZE_BYTES, NULL);
                          ^~~~~~~~~~~~~~~
                          arl_create
aclk/aclk_lws_wss_client.c:120:24: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  inst->read_ringbuffer = lws_ring_create(1, ACLK_LWS_WSS_RECV_BUFF_SIZE_BYTES, NULL);
                        ^
aclk/aclk_lws_wss_client.c: In function '_aclk_wss_connect':
aclk/aclk_lws_wss_client.c:159:21: error: 'LCCSCF_USE_SSL' undeclared (first use in this function); did you mean 'BIO_C_SET_SSL'?
  i.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;
                     ^~~~~~~~~~~~~~
                     BIO_C_SET_SSL
aclk/aclk_lws_wss_client.c:159:21: note: each undeclared identifier is reported only once for each function it appears in
aclk/aclk_lws_wss_client.c:159:38: error: 'LCCSCF_ALLOW_SELFSIGNED' undeclared (first use in this function); did you mean 'ACLK_SSL_ALLOW_SELF_SIGNED'?
  i.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      ACLK_SSL_ALLOW_SELF_SIGNED
aclk/aclk_lws_wss_client.c:159:64: error: 'LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK' undeclared (first use in this function)
  i.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED | LCCSCF_SKIP_SERVER_CERT_HOSTNAME_CHECK;
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aclk/aclk_lws_wss_client.c: In function 'received_data_to_ringbuff':
aclk/aclk_lws_wss_client.c:167:6: warning: implicit declaration of function 'lws_ring_insert'; did you mean 'lws_wsi_user'? [-Wimplicit-function-declaration]
  if( lws_ring_insert(buffer, data, len) != len ) {
      ^~~~~~~~~~~~~~~
      lws_wsi_user
aclk/aclk_lws_wss_client.c: In function 'aclk_lws_wss_callback':
aclk/aclk_lws_wss_client.c:241:7: error: 'LWS_CALLBACK_CLIENT_CLOSED' undeclared (first use in this function); did you mean 'LWS_CALLBACK_CLIENT_RECEIVE'?
  case LWS_CALLBACK_CLIENT_CLOSED:
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
       LWS_CALLBACK_CLIENT_RECEIVE
aclk/aclk_lws_wss_client.c: In function '_aclk_wss_connect':
aclk/aclk_lws_wss_client.c:163:2: warning: ignoring return value of 'lws_client_connect_via_info', declared with attribute warn_unused_result [-Wunused-result]
  lws_client_connect_via_info(&i);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by amoss** [comment]
Systems with older libwebsockets installations will be covered by a different approach.
