### PR TITLE
Fix nanosleep on platforms other than Linux

### LINKED ISSUE #12981: [Bug]: Failed to build/compile in MacOS 12.4 Monterey
### Bug description

Tried to install NetData agent on MacOS 12.4 Monterey but always getting an error. See log below:

`libnetdata/clocks/clocks.c:192:19: error: implicit declaration of function 'clock_nanosleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    while( (ret = clock_nanosleep(clock, TIMER_ABSTIME, &req, NULL)) != 0 ) {
                  ^
libnetdata/clocks/clocks.c:192:19: note: did you mean 'clock_sleep'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/mach.h:137:25: note: 'clock_sleep' declared here
extern kern_return_t    clock_sleep(mach_port_t,
                        ^
libnetdata/clocks/clocks.c:192:42: error: use of undeclared identifier 'TIMER_ABSTIME'
    while( (ret = clock_nanosleep(clock, TIMER_ABSTIME, &req, NULL)) != 0 ) {
                                         ^
libnetdata/clocks/clocks.c:347:21: error: implicit declaration of function 'clock_nanosleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    while ((errno = clock_nanosleep(CLOCK_REALTIME, 0, &req, &rem)) != 0) {
                    ^
3 errors generated.
make[2]: *** [libnetdata/clocks/clocks.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
`

### Expected behavior

Install NetData agent on MacOS.

### Steps to reproduce

1. Run the NetData agent install script provided for MacOS
2. Script starts compiling and building all required.
3. Failed to compile or build saying there is an error (see log details on the description)
...

### Installation method

kickstart.sh

### System info

```shell
Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 23:20:12 PDT 2022; root:xnu-8020.121.3~5/RELEASE_X86_64 x86_64
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F5071b
```

### Netdata build info

```shell
Failed to install Netdata
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
`clock_nanosleep()` [isn't available](https://www.gnu.org/software/gnulib/manual/html_node/clock_005fnanosleep.html) on old FreeBSD versions and macOS. Moreover `clock_nanosleep(CLOCK_REALTIME, 0, &req, &rem)` doesn't differ from `nanosleep(&req, &rem)`. Thus, we will use `clock_nanosleep` only on Linux systems.

Fixes #12981

##### Test Plan
Build Netdata on Linux, macOS, and FreeBSD. Check if there are no compilation errors.

### CODE REVIEW

**Review by surajnpn — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
I tested this PR on `Slackware current` and `FreeBSD 13.1-RELEASE` and everything works, LGTM!
