### ISSUE TITLE
Dynamic lines for custom python.d plugin problem/help

### ISSUE THREAD

**Issue by mind-code** [netdata/netdata#2206]
I want to display the disk usage by user of a quota enabled XFS disk. I generate a quota report file via cronjob every minute and the resulting file (/scratch.report) looks like this:

```
root      16          0          0     00 [--------]
user1     307200          0          0     00 [--------]
user2     524332          0          0     00 [--------]
user3     1024000          0          0     00 [--------]
user4     716800          0          0     00 [--------]
```

I want to parse this file via a python.d plugin. Since I dont know which users will appear the lines have to be dynamically added like in other plugins for example the Apps-Plugin users.cpu chart.

This is the code I have so far:

```php
from base import ExecutableService
import msg

# default module values (can be overridden per job in `config`)
#update_every = 10
priority = 60000
retries = 60


# charts order (can be overridden if you want less charts, or different order)
ORDER = ['userdiskusage']

CHARTS = {
    'userdiskusage': {
        'options': [None, "User Disk Usage", "MB", None, 'usersdiskusage', 'stacked'],
        'lines': [

        ]}
}


class Service(ExecutableService):
    def __init__(self, configuration=None, name=None):
        ExecutableService.__init__(self, configuration=configuration, name=name)
        self.command = "cat /scratch.report"
        self.order = ORDER
        self.definitions = CHARTS

    def _get_data(self):
        """
        Format data received from shell command
        :return: dict
        """

        data = {}
        raw = []
        raw = self._get_raw_data()

        for line in raw:
          line = line.strip()

          if line:
            spl = line.split()
            data[spl[0]] = str(int(spl[1])//1024)

        for key in data:
          #self.definitions[ORDER[0]]['lines'].append([key])
          self.definitions[ORDER[0]]['lines'].append([key, None, 'absolute'])

        try:
            return data
        except (ValueError, AttributeError):
            return None
```

This works, but I have one problem. If a new users comes along and writes something, the lines wont get updated. The report file is correctly updated, but the netdata graph will keep the lines added on first start. It will update the values for theses lines accordingly, just not add new ones.

Any help with this would be greatly appreciated!!

**Comment by mind-code** [comment]
Ok I got a hint myself .... when running debug and adding a newuser file I get this error:
```
python.d ERROR: userdiskusage wrong dimension id: NEWUSER Available dimensions are: olduser1 olderuser2 ....
```

So it appears I have to dynamically adjust dimensions. Is this possible? Ill keep trying, but If somebody can help quickly, Id still appreciate it greatly :)

**Comment by ktsaou** [comment]
There are many plugins that do that. I recall web_log for example.
But @l2isbad knows for sure...

**Comment by mind-code** [comment]
Thank you for your comment, but that plugin looks rather ... complicated.

I oriented my code up there on **redis.chart.py** the "keys" chart. I have not used that plugin in practice, but the code and comments look like its what im looking for.

It feels like Im almost there and am just missing a line or two to update the dimensions on each update.

**Comment by l2isbad** [comment]
@mind-code 

Try this:

```python
# -*- coding: utf-8 -*-
# Description: .........................
from os.path import basename
from base import SimpleService

# default module values (can be overridden per job in `config`)
priority = 60000
retries = 60

# charts order (can be overridden if you want less charts, or different order)
NAME = basename(__file__).split('.')[0]
ORDER = ['user_disk_usage']

CHARTS = {
    'user_disk_usage': {
        'options': [None, "User Disk Usage", "MB", None, '%s.usage' % NAME, 'stacked'],
        'lines': []}
}


class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.path = '/PATH/TO/REPORT'  # !!!!!!!!!!!!!!!!
        self.custom_chart = 'CHART %s.user_disk_usage' \
                            ' "" "User Disk Usage" MB "disk usage"' \
                            ' %s.usage stacked 60000 %s\n' % (NAME,
                                                              NAME, self.update_every)

    def check(self):
        return self._get_data() or False

    def _get_raw_data(self):
        try:
            with open(self.path) as f:
                return f.readlines() or None
        except (OSError, IOError):
            return None

    def _get_data(self):
        """
        Format data received from shell command
        :return: dict
        """
        raw_data = self._get_raw_data()
        if not raw_data:
            return None

        data = dict()
        for row in raw_data:
            try:
                row = row.split()
                user, usage = row[0], int(row[1])
                if user not in self._dimensions:
                    self.add_new_dimension(user, [user, user, 'absolute', 1, 1 << 20])
                data[user] = usage
            except (ValueError, IndexError, TypeError):
                continue

        return data or None

    def add_new_dimension(self, dimension, line_list):
        line_list = list(map(str, line_list))
        self._dimensions.append(dimension)
        self.definitions['user_disk_usage']['lines'].append(line_list)
        chart = self.custom_chart + "DIMENSION %s\n" % ' '.join(line_list)
        print(chart)
```

**Comment by mind-code** [comment]
Thank you, you rock!!!

I see that you switched the SimpleService. Interesting. I dont care which one is used and since this doesnt depend on cat being there its probably better, but just for understanding sake this could work with the ExecutableService too right?

Anyway thank you a lot!! I was really reluctant to come here with a question and not a bug, but Im glad I did. 

 :thumbsup:

**Comment by l2isbad** [comment]
> this could work with the ExecutableService too right?

Yes

You are welcome 😄

**Comment by mind-code** [comment]
The provided solution stopped working in netdata 1.10.0 (maybe earlier) .. the version I had this running on in production was 1.6.0.

When using the above plugin in 1.10.0 I get the following error:

```
2018-10-09 16:33:27: python.d ERROR: scratch_usage: scratch_usage: check() unhandled exception: 'Service' object has no attribute '_dimensions'
2018-10-09 16:33:27: python.d INFO: scratch_usage: scratch_usage: check() => [FAILED]
```

So it appears something changed with the SimpleService class, maybe its really trivial and just a rename of the _dimensions attribute?

I did a little bit of searching, but couldnt find any obvious result that would point me into the right direction. Any help would be greatly appreciated.

**Comment by mind-code** [comment]
I did some further testing:

netdata-1.9.0: same error
netdata-1.8.0: working

So something that has changed in between those 2 version.

**Comment by l2isbad** [comment]
hi @mind-code 

try this

<details><summary>click me</summary>
<p>

```python
# -*- coding: utf-8 -*-
# Description: description

from collections import namedtuple
from os.path import basename

from bases.FrameworkServices.SimpleService import SimpleService

NAME = basename(__file__).split('.')[0]

ORDER = [
    'user_disk_usage',
]

CHARTS = {
    'user_disk_usage': {
        'options': [None, 'User Disk Usage', 'MB', 'disk usage', '{0}.disk_usage'.format(NAME), 'stacked'],
        'lines': []
    },
}

PARSED = namedtuple(
    "PARSED",
    [
        "user",
        "disk_usage",
    ]
)


class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.path = 'PATH/TO/REPORT'

    def check(self):
        raw = self.read_file()
        if not raw:
            return False
        return bool(self.parse_raw_data(raw))

    def get_data(self):
        data = dict()

        raw = self.read_file()
        if not raw:
            return None

        parsed = self.parse_raw_data(raw)

        if not parsed:
            return None

        for p in parsed:
            if p.user not in self.charts['user_disk_usage']:
                self.charts['user_disk_usage'].add_dimension([p.user, p.user, 'absolute', 1, 1 << 20])
            data[p.user] = p.disk_usage

        return data or None

    def read_file(self):
        try:
            with open(self.path) as f:
                return f.readlines()
        except (OSError, IOError) as error:
            self.debug(error)
            return None

    def parse_raw_data(self, raw):
        parsed = list()
        for row in raw:
            row = row.split()
            try:
                parsed.append(PARSED(row[0], int(row[1])))
            except (ValueError, IndexError, TypeError) as error:
                self.debug(error)
                continue
        return parsed

```

</p>
</details>

**Comment by mind-code** [comment]
@l2isbad again, what am I supposed to say besides: Thank you, you rock!!! 

Seriously, since this is not a bug I know that any help on this is not a given and I greatly appreciate you taking the time to help me with this!

I realized yesterday after testing the different netdata version and looking and the commit log of the python base clases, that a lot had changed in the codebase. I also found the new example and that looked promising, but it was late yesterday (EU here) and so I gave up for the day. 

Thank you, and know that im a vocal ambassador for netdata around here ;)
