### ISSUE TITLE
Can't use dashboards directly since registration for cloud

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata#9736]
##### Bug report summary

I'm monitoring 50+ hosts in different data centers for years and I usually went to http://ip:19999 to access the dashboard. The host's firewall keeps that port open open just for my local IP.

Since I registered all of the hosts into Netdata's cloud service, that direct dashboard doesn't work anymore. On some hosts it just loads the start screen, on others it also loads the sections but not the charts.

On one of the hosts where it only loads the start screen with "netdata" in the screen center, I see an error message in the browser's console:

```
dashboard-react.js:542 Uncaught TypeError: NETDATA.error is not a function
    at Object.<anonymous> (dashboard-react.js:542)
    at l (jquery.js:3291)
    at Object.fireWith [as rejectWith] (jquery.js:3421)
    at E (jquery.js:9535)
    at XMLHttpRequest.<anonymous> (jquery.js:9785)
(anonymous) @ dashboard-react.js:542
```

Going to the network tab of the console, I see all components loading with a 200 response code.

##### OS / Environment

Both client and server are on Ubuntu 18.04 LTS

##### Netdata version

1.24.0

**Comment by jurgenhaas** [comment]
OK, this one can be closed because the error was caused by #9737 and the other part of loading the dashboard but not the charts was only a delay of loading caused by an old registry configuration left in netdata.conf from prior the cloud age.

**Comment by okgolove** [comment]
I got the same when I changed hostname one of my child nodes. Cloud is not enabled.

**Comment by okgolove** [comment]
Interesting, this happens because of wrong symbols in hostname. Should not Netdata check hostname using dns regex?
