### ISSUE TITLE
python.d/dockerd plugin update error

### ISSUE THREAD

**Issue by jdelvecchio** [netdata/netdata#5200]
##### Bug report summary
Hi,

I'm trying to monitor healthy/unhealthy containers with the python.d/dockerd plugin but I get this error :
```
2019-01-17 14:49:24: python.d INFO: dockerd: local: check() => [OK]
2019-01-17 14:49:26: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:27: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:28: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:29: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:30: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:33: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:36: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:39: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:42: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:45: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
2019-01-17 14:49:51: python.d ERROR: dockerd: local: update() unhandled exception: list() got an unexpected keyword argument 'sparse'
```

The initial check seems ok but the update doesn't work. No charts and alarms are configured with dockerd.

##### OS / Environment
Ubuntu 18.04
Netdata commit version a67afbe

##### Component Name
python.d/dockerd

##### Steps To Reproduce
Install Netdata
Install docker-ce and docker packages
Install python-docker package (with apt)

##### Expected behavior
The dockerd plugin works and starts monitoring health/unhealthy containers

**Comment by jdelvecchio** [comment]
Got it fixed by installer python-docker with pip instead of system packages.

What version of python-docker is required for this module to work ?

**Comment by ilyam8** [comment]
@jdelvecchio 

Good question.

cc: @tuxity 

> What version of python-docker is required for this module to work ?

According `docker` [changelog](https://docker-py.readthedocs.io/en/stable/change-log.html) minimum required version is 3.2.0 ( i see `Added sparse argument to DockerClient.containers.list()`)

**Comment by ilyam8** [comment]
Ye, ubuntu `18.04` has 2.5.1
https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=python-docker

**Comment by tuxity** [comment]
Hello,

Which version of docker do you have ? 

I work with recent ones (Docker version 18.09.0, build 4d60db4, for ex) and no problems using pip `docker` package
They recently rename the pip package to `docker`, before it was called `docker-py`

**Comment by ilyam8** [comment]
@tuxity i think we need to add minimum version req to module readme + check version in `check`

**Comment by ilyam8** [comment]
@tuxity and it was a super quick response :+1:  i expected it will take some time because of your github status :smile:

**Comment by tuxity** [comment]
@ilyam8 Yes, I think something like that should be added, or adapt the code to handle older docker api (without sparse in this case). No time to do a fix and tests, I will let you handle this.

**Comment by jdelvecchio** [comment]
I had python-docker 2.5.1
I uninstalled it and installed python-docker with pip :
`pip install docker` 

I don't think the proper "docker" version here was the problem, only the python-docker package

**Comment by ilyam8** [comment]
fixed in #5217
