### PR TITLE
Add a checkpoint message to alerts stream

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR adds a new `AlarmCheckpoint` message to the alerts stream. The purpose of the message is to do a check on both the cloud and the agent of the currently active alerts.

The Alert checkpoint will be requested and triggered from the cloud on start (or child connection) and then periodically. Upon receiving the request, the agent will calculate a checksum of the current raised alerts and send it to the cloud. The cloud itself will calculate the same, and if they don't match, a snapshot will be requested.

The calculation should be done at a point where there are no pending events to be sent to the cloud, at the end of the health loop for the host requested.

Other changes of this PR:

* The `AlarmLogHealth` message is deprecated. There will be no exchange of it with the cloud.
* `Sequence` and `batch` ids are deprecated. Cloud will be able to process alert events out of order, but based on their `when` timestamps. We will keep though the `sequence_id` internally.
* No acknowledgments of received sequence_ids by the cloud.
* On a clean start, or when the cloud's database for a host for alerts is empty (e.g. because the user has deleted the node, then started it again) we will still delete our queue and queue all existing alerts. This is for the cloud to maintain it's configured alerts page. We plan to remove it once the configured alerts can be retrieved by an api call from an agent.
* Health enabled has been moved to the capabilities. This is the way for the cloud to trigger whether or not to start alerts stream.

##### Test Plan

Right now the respective cloud changes are only available on testing environment at a needed basis.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by MrZammler** [comment]
Cloud implementation has been deployed to production, SET test suite passed.

File: database/sqlite/sqlite_aclk_alert.c [hunk 1]
```diff
@@ -1124,3 +989,140 @@ int get_proto_alert_status(RRDHOST *host, struct proto_alert_status *proto_alert
...
+        }
+    } else {
+        alarms_to_hash = buffer_create(1, NULL);
+        buffer_strcat(alarms_to_hash, "");
+        len = 0;
+    }
+
+    unsigned char hash[SHA256_DIGEST_LENGTH + 1];
+    SHA256_CTX sha256;
+    SHA256_Init(&sha256);
```
Comment (thiagoftsm) [inline database/sqlite/sqlite_aclk_alert.c:1112]: Hello @MrZammler ,

On newer OpenSSL versions we have warnings like these:

```sh
database/sqlite/sqlite_aclk_alert.c:1112:5: warning: 'SHA256_Init' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1112 |     SHA256_Init(&sha256);
      |     ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from ./libnetdata/socket/security.h:27,
                 from ./libnetdata/libnetdata.h:651,
                 from ./daemon/common.h:6,
                 from database/sqlite/sqlite_functions.h:6,
                 from database/sqlite/sqlite_aclk_alert.c:3:
/usr/include/openssl/sha.h:73:27: note: declared here
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
database/sqlite/sqlite_aclk_alert.c:1113:5: warning: 'SHA256_Update' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1113 |     SHA256_Update(&sha256, buffer_tostring(alarms_to_hash), len);
      |     ^~~~~~~~~~~~~
/usr/include/openssl/sha.h:74:27: note: declared here
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
database/sqlite/sqlite_aclk_alert.c:1114:5: warning: 'SHA256_Final' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 1114 |     SHA256_Final(hash, &sha256);
      |     ^~~~~~~~~~~~
/usr/include/openssl/sha.h:76:27: note: declared here
   76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
      |                           ^~~~~~~~~~~~
```

please, take a look when you have a time.

Comment (thiagoftsm) [reply database/sqlite/sqlite_aclk_alert.c:1112]: Except for these warnings that we need to address, the PR is working as expected.

Comment (MrZammler) [reply database/sqlite/sqlite_aclk_alert.c]: Thank you Thiago! Yes, dumb did not check on openssl 3... changed!

**Comment by thiagoftsm** [comment]
Hello @MrZammler ,

I could compile without warnings with latest `OpenSSL` , on the other hand when I tried to compile using `OpenSSL 1.02` on `CentOS 7.9` the compilation did not finish with the following errors:

```sh
libnetdata/libnetdata.c: In function 'hash256_string':
libnetdata/libnetdata.c:2180:5: warning: implicit declaration of function 'EVP_MD_CTX_new' [-Wimplicit-function-declaration]
     ctx = EVP_MD_CTX_new();
     ^
libnetdata/libnetdata.c:2180:9: warning: assignment makes pointer from integer without a cast [enabled by default]
     ctx = EVP_MD_CTX_new();
         ^
libnetdata/libnetdata.c:2186:9: warning: implicit declaration of function 'EVP_MD_CTX_free' [-Wimplicit-function-declaration]
         EVP_MD_CTX_free(ctx);
         ^
In file included from ./database/engine/rrdengineapi.h:6:0,
                 from ./database/rrd.h:1352,
                 from ./daemon/global_statistics.h:6,
                 from ./daemon/common.h:36,
                 from ./daemon/main.h:6,
                 from libnetdata/log/log.c:3:
./database/engine/rrdengine.h: In function 'journal_metric_uuid_compare':
./database/engine/rrdengine.h:519:50: warning: passing argument 1 of 'uuid_memcmp' from incompatible pointer type [enabled by default]
     return uuid_memcmp((uuid_t *)key, &(((struct journal_metric_list *) metric)->uuid));
                                                  ^
In file included from ./libnetdata/libnetdata.h:645:0,
                 from ./daemon/common.h:6,
                 from ./daemon/main.h:6,
                 from libnetdata/log/log.c:3:
./libnetdata/inlined.h:513:19: note: expected 'const unsigned char (*)[16]' but argument is of type 'unsigned char (*)[16]'
 static inline int uuid_memcmp(const uuid_t *uu1, const uuid_t *uu2) {
                   ^
In file included from ./database/engine/rrdengineapi.h:6:0,
                 from ./database/rrd.h:1352,
                 from ./daemon/global_statistics.h:6,
                 from ./daemon/common.h:36,
                 from ./daemon/main.h:6,
                 from libnetdata/log/log.c:3:
./database/engine/rrdengine.h:519:50: warning: passing argument 2 of 'uuid_memcmp' from incompatible pointer type [enabled by default]
     return uuid_memcmp((uuid_t *)key, &(((struct journal_metric_list *) metric)->uuid));
....

In file included from libnetdata/json/../libnetdata.h:645:0,
                 from libnetdata/json/json.c:2:
libnetdata/json/../inlined.h:513:19: note: expected 'const unsigned char (*)[16]' but argument is of type 'unsigned char (*)[16]'
 static inline int uuid_memcmp(const uuid_t *uu1, const uuid_t *uu2) {
                   ^
libnetdata/libnetdata.o: In function `hash256_string':
libnetdata.c:(.text+0x2556): undefined reference to `EVP_MD_CTX_new'
libnetdata.c:(.text+0x25b6): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
```

Please, take a look when you have a time.

**Review by stelfrag — APPROVED** [review]
