### ISSUE TITLE
[Bug]: netdata 1.46.1 fails to build on FreeBSD 14.0 amd64

### ISSUE THREAD

**Issue by mrdaemon** [netdata/netdata#17995]
### Bug description

The netdata agent fails to build either via cron or when kickstart is invoked manually on FreeBSD 14.0.

There are many errors and finding the root one is difficult, but it seems to start with a series of:

```
/context_stream.cc.o.d -o CMakeFiles/netdata.dir/src/aclk/schema-wrappers/context_stream.cc.o -c /tmp/netdata-updater-XXXXXXXXXX.OmaqweibGI/netdata-v1.46.1/src/aclk/schema-wrappers/context_stream.cc
In file included from /tmp/netdata-updater-XXXXXXXXXX.OmaqweibGI/netdata-v1.46.1/src/aclk/schema-wrappers/connection.cc:3:
/tmp/netdata-updater-XXXXXXXXXX.OmaqweibGI/netdata-v1.46.1/src/aclk/aclk-schemas/proto/agent/v1/connection.pb.h:15:2: error: "This file was generated by a newer version of protoc which is"
#error "This file was generated by a newer version of protoc which is"
 ^
/tmp/netdata-updater-XXXXXXXXXX.OmaqweibGI/netdata-v1.46.1/src/aclk/aclk-schemas/proto/agent/v1/connection.pb.h:16:2: error: "incompatible with your Protocol Buffer headers. Please update"
#error "incompatible with your Protocol Buffer headers. Please update"
 ^
/tmp/netdata-updater-XXXXXXXXXX.OmaqweibGI/netdata-v1.46.1/src/aclk/aclk-schemas/proto/agent/v1/connection.pb.h:17:2: error: "your headers."
#error "your headers."
 ^
```

Then a series of missing members in a namespace

```
In file included from /usr/local/include/absl/container/internal/compressed_tuple.h:40:
/usr/local/include/absl/utility/utility.h:164:12: error: no member named 'in_place_t' in namespace 'std'
using std::in_place_t;
      ~~~~~^
/usr/local/include/absl/utility/utility.h:165:12: error: no member named 'in_place' in namespace 'std'
using std::in_place;
      ~~~~~^
/usr/local/include/absl/utility/utility.h:181:12: error: no member named 'in_place_type' in namespace 'std'
using std::in_place_type;
      ~~~~~^
/usr/local/include/absl/utility/utility.h:182:12: error: no member named 'in_place_type_t' in namespace 'std'
using std::in_place_type_t;
      ~~~~~^
/usr/local/include/absl/utility/utility.h:198:12: error: no member named 'in_place_index' in namespace 'std'
using std::in_place_index;
      ~~~~~^
/usr/local/include/absl/utility/utility.h:199:12: error: no member named 'in_place_index_t' in namespace 'std'
using std::in_place_index_t;
      ~~~~~^
```

And this repeats for multiple modules afterwards until cmake decides there's too many errors and gives up.

The full build log can be found as gist below.

### Expected behavior

I would expect the agent to compile and produce a working binary

### Steps to reproduce

1. run kickstart with --stable and any important parameters
2. wait
3. Observe failure
...

### Installation method

kickstart.sh

### System info

```shell
FreeBSD okami.lab.underwares.org 14.0-RELEASE-p6 FreeBSD 14.0-RELEASE-p6 #0: Tue Mar 26 20:26:20 UTC 2024     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
1400097
```

### Netdata build info

```shell
NOTE: This is for the previous version of netdata that built fine
Packaging:
    Netdata Version ____________________________________________ : v1.45.5
    Installation Type __________________________________________ : kickstart-build
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /usr/local/etc/netdata
    Stock Configurations _______________________________________ : /usr/local/usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /usr/local/var/cache/netdata
    Permanent Databases ________________________________________ : /usr/local/var/lib/netdata
    Plugins ____________________________________________________ : /usr/local/usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/local/usr/share/netdata/web
    Log Files __________________________________________________ : /usr/local/var/log/netdata
    Lock Files _________________________________________________ : /usr/local/var/lib/netdata/lock
    Home _______________________________________________________ : /usr/local/var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : FreeBSD
    Kernel Version _____________________________________________ : 1400097
    Operating System ___________________________________________ : FreeBSD
    Operating System ID ________________________________________ : FreeBSD
    Operating System ID Like ___________________________________ : FreeBSD
    Operating System Version ___________________________________ : 14.0-RELEASE-p6
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : uname
Hardware:
    CPU Cores __________________________________________________ :
    CPU Frequency ______________________________________________ : unknown
    RAM Bytes __________________________________________________ : 68607893504
    Disk Capacity ______________________________________________ : 150743868076032
    CPU Architecture ___________________________________________ : amd64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : sysctl
Container:
    Container __________________________________________________ : unknown
    Container Detection ________________________________________ : none
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : FreeBSD
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (bundled)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : NO
    cgroup-network (associate interfaces to CGROUPS) ___________ : NO
    proc (monitor Linux systems) _______________________________ : NO
    tc (monitor Linux network QoS) _____________________________ : NO
    diskspace (monitor Linux mount points) _____________________ : NO
    freebsd (monitor FreeBSD systems) __________________________ : YES
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : NO
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : NO
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : NO
    slabinfo (monitor kernel object caching) ___________________ : NO
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

Full build log is available here:

https://gist.githubusercontent.com/mrdaemon/3f7a190fb1eaf5c8e90fcd399a70c2a8/raw/d06b526afe2b3029cef6be2e01b16b402d028066/netdata-build.log
