### PR TITLE
[WIP] Workers utilization charts

### PR DESCRIPTION
**Pull request by ktsaou**
We have various worker threads, like web server, aclk query, aclk sync, dbengine, etc.

This PR adds worker utilization charts (the % of time they are busy, the number of jobs done and currently running, the number of threads available and busy - 3 charts total).

TODO: Currently  aclk query threads are not monitored

There is also another set of workers, the libuv workers, however it does not seem technically possible to monitor them currently.

WIP. More are coming...

### CODE REVIEW

**Comment by ktsaou** [comment]
Ready for review

**Review by vlvkobal — DISMISSED** [review]
Please remove the commented mutexes.

File: libnetdata/worker_utilization/worker_utilization.c [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+
+    // netdata_mutex_lock(&worker->lock);
+    usec_t now = now_realtime_usec();
+
+    worker->last_action_timestamp = now;
+    worker->last_action = WORKER_BUSY;
+
+    // netdata_mutex_unlock(&worker->lock);
+}
+
```
Comment (thiagoftsm) [inline libnetdata/worker_utilization/worker_utilization.c:103]: @vlvkobal already addressed the [commented mutex](https://github.com/netdata/netdata/pull/12807#pullrequestreview-960508966) above, and right now I am seeing blank lines without code or comment, I think this could be a typo error, if it is, please, remove it.

**Comment by thiagoftsm** [comment]
@ilyam8 and @cpipilas a suggestion for future PRs that has relationship with this PR. I observed that we do not have descriptions on top of some charts in `Netdata monitoring` section. It will be better for our users to have descriptions for these charts.

**Comment by thiagoftsm** [comment]
PR is working as expected on Linux and FreeBSD, I am only waiting for the minor comments to be addressed to approve it.

**Review by stelfrag — DISMISSED** [review]

**Review by vkalintiris — APPROVED** [review]

**Review by stelfrag — DISMISSED** [review]

**Comment by vlvkobal** [comment]
Valgrind reports a lot of errors like
```
==12502== Conditional jump or move depends on uninitialised value(s)
==12502==    at 0x14D8A3: pack_storage_number (storage_number.c:88)
==12502==    by 0x190493: rrdset_done_interpolate (rrdset.c:1253)
==12502==    by 0x195443: rrdset_done (rrdset.c:1802)
==12502==    by 0x11F9F6: worker_utilization_update_chart (global_statistics.c:1047)
==12502==    by 0x121677: worker_utilization_charts (global_statistics.c:1152)
==12502==    by 0x12175D: global_statistics_main (global_statistics.c:1183)
==12502==    by 0x14DF58: thread_start (threads.c:185)
==12502==    by 0x50915C1: start_thread (in /usr/lib/libc.so.6)
==12502==    by 0x5116583: clone (in /usr/lib/libc.so.6)
```
and Netdata crashes after some time.

**Comment by ktsaou** [comment]
@vlvkobal please check again. It should be fixed.

File: daemon/global_statistics.c [hunk 2]
```diff
@@ -436,435 +436,952 @@ static void global_statistics_charts(void) {
...
-            rrddim_set_by_pointer(st_long_term_pages, rd_flushing_pressure_deletions,
-                                  (collected_number)stats_array[36]);
-            rrdset_done(st_long_term_pages);
         }
+    }
+#endif
+}
+
+static void update_heartbeat_charts() {
+    RRDSET *st = rrdset_create_localhost(
```
Comment (stelfrag) [inline daemon/global_statistics.c:841]: Chart and dimensions need to be static

**Review by andrewm4894 — DISMISSED** [review]
Should be very useful for the ML charts.

**Review by stelfrag — APPROVED** [review]

File: libnetdata/clocks/clocks.c [hunk 3]
```diff
@@ -155,105 +173,184 @@ inline usec_t dt_usec(struct timeval *now, struct timeval *old) {
...
+static size_t heartbeat_alignment_id = 0;
+
+struct heartbeat_thread_statistics {
+    size_t sequence;
+    usec_t dt;
+};
+static struct heartbeat_thread_statistics heartbeat_alignment_values[HEARTBEAT_ALIGNMENT_STATISTICS_SIZE] = { 0 };
+
+void heartbeat_statistics(usec_t *min_ptr, usec_t *max_ptr, usec_t *average_ptr, size_t *count_ptr) {
+    struct heartbeat_thread_statistics new[HEARTBEAT_ALIGNMENT_STATISTICS_SIZE];
```
Comment (thiagoftsm) [inline libnetdata/clocks/clocks.c:234]: I remember in the past we had PRs adjusting our code renaming variables that were reserved keywords in another development language, so to avoid problems for these users that can contribute for the project and use this function in a c++ file, please, rename `new` that is a keyword for `c++`.

File: libnetdata/clocks/clocks.c [hunk 4]
```diff
@@ -155,105 +173,184 @@ inline usec_t dt_usec(struct timeval *now, struct timeval *old) {
...
-
-    usec_t next_monotonic = now.monotonic - (now.monotonic % tick) + tick;
-
-    while(now.monotonic < next_monotonic) {
-        sleep_usec(next_monotonic - now.monotonic);
-        now.monotonic = now_monotonic_usec();
-        now.realtime  = now_realtime_usec();
+    if(unlikely(hb->randomness > tick / 2)) {
+        // TODO: The heartbeat tick should be specified at the heartbeat_init() function
+        usec_t new = (now_realtime_usec() * clock_realtime_resolution) % (tick / 2);
```
Comment (thiagoftsm) [inline libnetdata/clocks/clocks.c:289]: The same suggestion I gave above is also applied here.

File: daemon/global_statistics.c [hunk 5]
```diff
@@ -436,435 +436,953 @@ static void global_statistics_charts(void) {
...
     }
+
+    struct worker_thread *wt;
+    for(wt = wu->threads; wt ; wt = wt->next) {
+        wt->enabled = 0;
+        wt->cpu_enabled = 0;
+    }
+}
+
+static int read_thread_cpu_time_from_proc_stat(pid_t pid, kernel_uint_t *utime, kernel_uint_t *stime) {
```
Comment (thiagoftsm) [inline daemon/global_statistics.c:1196]: On `FreeBSD` we are receiving this warnings:

```sh
daemon/global_statistics.c:1196:96: warning: unused parameter 'stime' [-Wunused-parameter]
 1196 | static int read_thread_cpu_time_from_proc_stat(pid_t pid, kernel_uint_t *utime, kernel_uint_t *stime) {
      |                                                                                 ~~~~~~~~~~~~~~~^~~~~
```

Please, add :
```sh
UNUSED(stime); 
UNUSED(utime); 
UNUSED(pid);
``` 
after `#else`

**Review by thiagoftsm — CHANGES_REQUESTED** [review]
To remove the function `heartbeat_monotonic_dt_to_now_usec` won't allow us to compile `netdata` on `FreeBSD`:

```sh
~/collectors/freebsd.plugin/plugin_freebsd.c:122: undefined reference to `heartbeat_monotonic_dt_to_now_usec'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:5179: netdata] Error 1
gmake[1]: *** [Makefile:6459: all-recursive] Error 1
gmake: *** [Makefile:3528: all] Error 2
 FAILED  ''

 ABORTED  Failed to build Netdata. 
``` 

Please, change `freebsd_plugin` to be compatible with the current changes.

**Comment by ktsaou** [comment]
Addressed all your comments @thiagoftsm 
Please review again.

I have not tested FreeBSD and MacOS. Please do if you can.

**Comment by ilyam8** [comment]
@ktsaou I think we need to adjust the context of the charts: `netdata.NAME.workers.time` => `netdata.workers.time` etc. As it is all the worker charts with the same context will be merged into one on the Cloud overview page (e.g. plugins.d workers by type with idlejitter workers by ty type).

**Review by ilyam8 — APPROVED** [review]
This branch has been running on 2 parent instances (Linux) with 20 children and connected to the Netdata Cloud. Works great. I haven't reviewed the code.

**Review by thiagoftsm — APPROVED** [review]
I tested now on FreeBSD and Linux and everything is working as expected, I am approving the PR, but I will give a suggestion to wait somebody that has Mac to test it before merge.

**Review by stelfrag — APPROVED** [review]

**Comment by iigorkarpov** [comment]
Works on freebsd13 13.0-RELEASE-p8 amd64

**Comment by iigorkarpov** [comment]
The master can be successfully compiled and run on macOS Monterrey Darwin Kernel Version 21.4.0 (very recent one), but no workers entry are shown in dashboard.
